//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SMatch/MatchService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "match.grpc.pb.h"
#include "MatchService_Private.generated.h"

class UMatch::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::match::Match::Stub> Stub;
};


UCLASS()
class UMatchGetDestinationLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UMatchClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcMatchMatchResponse& Response);
public:
	FGrpcContextHandle Handle;
	UMatch::FGetDestinationResponseLambda ResponseLambda;
};

UCLASS()
class UMatchUpdateToMatchmakerLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UMatchClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcMatchUpdateResponse& Response);
public:
	FGrpcContextHandle Handle;
	UMatch::FUpdateToMatchmakerResponseLambda ResponseLambda;
};

UCLASS()
class UMatchRemoveFromMatchmakerLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UMatchClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcMatchRemoveResponse& Response);
public:
	FGrpcContextHandle Handle;
	UMatch::FRemoveFromMatchmakerResponseLambda ResponseLambda;
};

