//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SMatch/MatchMessage.h"
#include "MatchClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnMatchGetDestinationResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcMatchMatchResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnMatchUpdateToMatchmakerResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcMatchUpdateResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnMatchRemoveFromMatchmakerResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcMatchRemoveResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UMatchClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnMatchGetDestinationResponse OnGetDestinationResponse;

	UPROPERTY(BlueprintAssignable)
	FOnMatchUpdateToMatchmakerResponse OnUpdateToMatchmakerResponse;

	UPROPERTY(BlueprintAssignable)
	FOnMatchRemoveFromMatchmakerResponse OnRemoveFromMatchmakerResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetDestination();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetDestination(FGrpcContextHandle Handle, const FGrpcMatchEmpty& Request);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitUpdateToMatchmaker();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void UpdateToMatchmaker(FGrpcContextHandle Handle, const FGrpcMatchUpdateRequest& Request);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitRemoveFromMatchmaker();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void RemoveFromMatchmaker(FGrpcContextHandle Handle, const FGrpcMatchRemoveRequest& Request);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

