//Generated by TurboLink CodeGenerator, do not edit!
#include "SMatch/MatchMessage.h"
#include "TurboLinkGrpcContext.h"
#include "match.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::match::Empty* in, FGrpcMatchEmpty* out);
void TURBOLINK_TO_GRPC(const FGrpcMatchEmpty* in, ::match::Empty* out);

void GRPC_TO_TURBOLINK(const ::match::MatchResponse* in, FGrpcMatchMatchResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcMatchMatchResponse* in, ::match::MatchResponse* out);

void GRPC_TO_TURBOLINK(const ::match::UpdateRequest* in, FGrpcMatchUpdateRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcMatchUpdateRequest* in, ::match::UpdateRequest* out);

void GRPC_TO_TURBOLINK(const ::match::UpdateResponse* in, FGrpcMatchUpdateResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcMatchUpdateResponse* in, ::match::UpdateResponse* out);

void GRPC_TO_TURBOLINK(const ::match::RemoveRequest* in, FGrpcMatchRemoveRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcMatchRemoveRequest* in, ::match::RemoveRequest* out);

void GRPC_TO_TURBOLINK(const ::match::RemoveResponse* in, FGrpcMatchRemoveResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcMatchRemoveResponse* in, ::match::RemoveResponse* out);

typedef grpc::ClientAsyncResponseReader<::match::MatchResponse> Match_GetDestination_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::match::UpdateResponse> Match_UpdateToMatchmaker_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::match::RemoveResponse> Match_RemoveFromMatchmaker_ReaderWriter;
