//Generated by TurboLink CodeGenerator, do not edit!
#include "MatchService_Private.h"

void UMatchGetDestinationLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcMatchMatchResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetDestinationResponse.RemoveDynamic(this, &UMatchGetDestinationLambdaWrapper::OnResponse);
}

void UMatchUpdateToMatchmakerLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcMatchUpdateResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnUpdateToMatchmakerResponse.RemoveDynamic(this, &UMatchUpdateToMatchmakerLambdaWrapper::OnResponse);
}

void UMatchRemoveFromMatchmakerLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcMatchRemoveResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnRemoveFromMatchmakerResponse.RemoveDynamic(this, &UMatchRemoveFromMatchmakerLambdaWrapper::OnResponse);
}

