//Generated by TurboLink CodeGenerator, do not edit!
#include "SMatch/MatchMessage.h"
#include "SMatch/MatchMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcMatchEmpty, ::match::Empty)
DEFINE_JSON_FUNCTIONS(FGrpcMatchMatchResponse, ::match::MatchResponse)
DEFINE_JSON_FUNCTIONS(FGrpcMatchUpdateRequest, ::match::UpdateRequest)
DEFINE_JSON_FUNCTIONS(FGrpcMatchUpdateResponse, ::match::UpdateResponse)
DEFINE_JSON_FUNCTIONS(FGrpcMatchRemoveRequest, ::match::RemoveRequest)
DEFINE_JSON_FUNCTIONS(FGrpcMatchRemoveResponse, ::match::RemoveResponse)

