//Generated by TurboLink CodeGenerator, do not edit!
#include "MatchMarshaling.h"

void GRPC_TO_TURBOLINK(const ::match::Empty* in, FGrpcMatchEmpty* out)
{
}

void TURBOLINK_TO_GRPC(const FGrpcMatchEmpty* in, ::match::Empty* out)
{
}

void GRPC_TO_TURBOLINK(const ::match::MatchResponse* in, FGrpcMatchMatchResponse* out)
{
    out->MatchedServer=UTF8_TO_TCHAR(in->matched_server().c_str());
    out->Success=in->success();
}

void TURBOLINK_TO_GRPC(const FGrpcMatchMatchResponse* in, ::match::MatchResponse* out)
{
    out->set_matched_server(TCHAR_TO_UTF8(*(in->MatchedServer)));
    out->set_success(in->Success);
}

void GRPC_TO_TURBOLINK(const ::match::UpdateRequest* in, FGrpcMatchUpdateRequest* out)
{
    out->ServerAddress=UTF8_TO_TCHAR(in->server_address().c_str());
    out->NumCurrentClients=in->num_current_clients();
}

void TURBOLINK_TO_GRPC(const FGrpcMatchUpdateRequest* in, ::match::UpdateRequest* out)
{
    out->set_server_address(TCHAR_TO_UTF8(*(in->ServerAddress)));
    out->set_num_current_clients(in->NumCurrentClients);
}

void GRPC_TO_TURBOLINK(const ::match::UpdateResponse* in, FGrpcMatchUpdateResponse* out)
{
    out->Success=in->success();
}

void TURBOLINK_TO_GRPC(const FGrpcMatchUpdateResponse* in, ::match::UpdateResponse* out)
{
    out->set_success(in->Success);
}

void GRPC_TO_TURBOLINK(const ::match::RemoveRequest* in, FGrpcMatchRemoveRequest* out)
{
    out->ServerAddress=UTF8_TO_TCHAR(in->server_address().c_str());
}

void TURBOLINK_TO_GRPC(const FGrpcMatchRemoveRequest* in, ::match::RemoveRequest* out)
{
    out->set_server_address(TCHAR_TO_UTF8(*(in->ServerAddress)));
}

void GRPC_TO_TURBOLINK(const ::match::RemoveResponse* in, FGrpcMatchRemoveResponse* out)
{
    out->Success=in->success();
}

void TURBOLINK_TO_GRPC(const FGrpcMatchRemoveResponse* in, ::match::RemoveResponse* out)
{
    out->set_success(in->Success);
}

