//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SMatch/MatchMessage.h"
#include "SMatch/MatchMarshaling.h"
class GrpcContext_Match_GetDestination : public GrpcContext_Ping_Pong<Match_GetDestination_ReaderWriter, ::match::MatchResponse>
{
	friend class UMatchClient;
	typedef GrpcContext_Ping_Pong<Match_GetDestination_ReaderWriter, ::match::MatchResponse> Super;

private:
	void Call(const FGrpcMatchEmpty& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_Match_GetDestination(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_Match_UpdateToMatchmaker : public GrpcContext_Ping_Pong<Match_UpdateToMatchmaker_ReaderWriter, ::match::UpdateResponse>
{
	friend class UMatchClient;
	typedef GrpcContext_Ping_Pong<Match_UpdateToMatchmaker_ReaderWriter, ::match::UpdateResponse> Super;

private:
	void Call(const FGrpcMatchUpdateRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_Match_UpdateToMatchmaker(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_Match_RemoveFromMatchmaker : public GrpcContext_Ping_Pong<Match_RemoveFromMatchmaker_ReaderWriter, ::match::RemoveResponse>
{
	friend class UMatchClient;
	typedef GrpcContext_Ping_Pong<Match_RemoveFromMatchmaker_ReaderWriter, ::match::RemoveResponse> Super;

private:
	void Call(const FGrpcMatchRemoveRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_Match_RemoveFromMatchmaker(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

