//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "MatchMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Match.Empty"))
struct FGrpcMatchEmpty : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Match.MatchResponse"))
struct FGrpcMatchMatchResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString MatchedServer = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Success = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="Match.UpdateRequest"))
struct FGrpcMatchUpdateRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ServerAddress = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 NumCurrentClients = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Match.UpdateResponse"))
struct FGrpcMatchUpdateResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Success = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="Match.RemoveRequest"))
struct FGrpcMatchRemoveRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ServerAddress = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Match.RemoveResponse"))
struct FGrpcMatchRemoveResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Success = false;
};
