//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SMatch/MatchClient.h"
#include "MatchService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UMatch : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	UMatchClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UMatchClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcMatchMatchResponse& Response)> FGetDestinationResponseLambda;
	void CallGetDestination(const FGrpcMatchEmpty& Request, FGetDestinationResponseLambda ResponseLambda);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcMatchUpdateResponse& Response)> FUpdateToMatchmakerResponseLambda;
	void CallUpdateToMatchmaker(const FGrpcMatchUpdateRequest& Request, FUpdateToMatchmakerResponseLambda ResponseLambda);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcMatchRemoveResponse& Response)> FRemoveFromMatchmakerResponseLambda;
	void CallRemoveFromMatchmaker(const FGrpcMatchRemoveRequest& Request, FRemoveFromMatchmakerResponseLambda ResponseLambda);

public:
	class Private;
	Private* const d = nullptr;

public:
	UMatch();
	virtual ~UMatch();
};

